version: '2.4'
services:

    si-runtime:
      build: 
        context: ./dockerfiles/streaming-integrator/
        args:
          - BASE_IMAGE=wso2/wso2si:4.0.0
      healthcheck:
        test: ["CMD", "nc", "-z","localhost", "9443"]
        interval: 10s
        start_period: 30s
        retries: 20
      ports:
      - "8025:8025"
      - "9090:9090"
      mem_limit: 512m
      mem_reservation: 128M
      cpus: 0.5
